# Generated by Django 4.2.16 on 2024-11-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("high_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("r_id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("mobile", models.CharField(max_length=15)),
                ("p_address", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
