# Generated by Django 3.2.25 on 2024-11-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_app', '0003_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('i_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('image_name', models.CharField(max_length=255)),
                ('ipfs_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('key', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
