# Generated by Django 4.2.6 on 2025-01-20 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("high_app", "0004_auto_20241126_1747"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Images",
        ),
        migrations.RemoveField(
            model_name="users",
            name="p_address",
        ),
    ]
